apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: two-tier-app-hpa
  namespace: two-tier-ns
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: two-tier-app-dep

  minReplicas: 2
  maxReplicas: 5

  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
